# Button handler messages
unauthorized_user: "âŒ Báº¡n khÃ´ng thá»ƒ sá»­ dá»¥ng nÃºt nÃ y!"
button_disabled: "âŒ NÃºt nÃ y hiá»‡n Ä‘ang bá»‹ vÃ´ hiá»‡u hÃ³a!"

# Player button messages
player_buttons:
  play_resumed: "â–¶ï¸ ÄÃ£ tiáº¿p tá»¥c phÃ¡t"
  play_paused: "â¸ï¸ ÄÃ£ táº¡m dá»«ng"
  track_skipped: "â­ï¸ ÄÃ£ chuyá»ƒn bÃ i"
  track_previous: "â®ï¸ BÃ i trÆ°á»›c"
  playback_stopped: "â¹ï¸ ÄÃ£ dá»«ng phÃ¡t"
  queue_shuffled: "ğŸ”€ ÄÃ£ xÃ¡o trá»™n hÃ ng Ä‘á»£i"
  volume_changed: "ğŸ”Š Ã‚m lÆ°á»£ng: {volume}%"
  loop_disabled: "ğŸ” Láº·p láº¡i: Táº¯t"
  loop_track: "ğŸ”‚ Láº·p láº¡i: BÃ i hÃ¡t"
  loop_queue: "ğŸ” Láº·p láº¡i: HÃ ng Ä‘á»£i"
  autoplay_enabled: "ğŸ” Tá»± Ä‘á»™ng phÃ¡t: Báº­t"
  autoplay_disabled: "ğŸ” Tá»± Ä‘á»™ng phÃ¡t: Táº¯t"

# Extended player messages from old file
autoplay:
  on: "Tá»± phÃ¡t giá» Ä‘Ã£ **Báº¬T** â€” ThÆ°á»Ÿng thá»©c Ã¢m nháº¡c nhÃ©!"
  off: "Tá»± phÃ¡t giá» Ä‘Ã£ **Táº®T** â€” MÃ¬nh sáº½ khÃ´ng tá»± thÃªm nháº¡c ná»¯a."
  no_song: "KhÃ´ng cÃ³ bÃ i hÃ¡t nÃ o Ä‘ang phÃ¡t!"

loop:
  current: |
    <:loop:1220832757496811570> **Äang láº·p láº¡i {title}
    <:blankers:1220848705289064669><:sparkle:1220846124961890304> ThÆ°á»Ÿng thá»©c nhÃ©, {user}**
  all: "<:loop:1220832757496811570> **{user} Ä‘Ã£ báº­t cháº¿ Ä‘á»™ láº·p toÃ n bá»™ hÃ ng chá» (QUEUE)**"
  disabled: "<:wrong:1220876213896216686> **Cháº¿ Ä‘á»™ láº·p Ä‘Ã£ bá»‹ {user} Táº®T**"

previous:
  not_found: |
    <:warnings:1220876158254710936> **KhÃ´ng tÃ¬m tháº¥y bÃ i trÆ°á»›c trong hÃ ng chá»!
    <:blankers:1220848705289064669><:pop:1220849334606626946> HÃ£y dÃ¹ng /play Ä‘á»ƒ thÃªm bÃ i vÃ  giá»¯ khÃ´ng khÃ­ sÃ´i Ä‘á»™ng nhÃ©!**
  message: |
    <:replay:1220881274378653787>  **Quay láº¡i bÃ i trÆ°á»›c do {user}